import { StyleSheet } from "react-native";
import { ColorPalette } from "../context/ThemeContext";

export const getHomeStyles = (Colors: ColorPalette) =>
  StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: Colors.background },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      paddingHorizontal: 24,
      paddingTop: 20,
      paddingBottom: 20,
      backgroundColor: Colors.background,
    },
    title: { fontSize: 32, fontWeight: "bold", color: Colors.text, marginBottom: 4 },
    subtitle: { fontSize: 16, color: Colors.secondaryText },
    headerButtons: { flexDirection: "row", alignItems: "center", gap: 12 },
    addButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: Colors.primary,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: Colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 3,
    },
    addButtonText: { color: Colors.surface, fontSize: 24, fontWeight: "bold", lineHeight: 28 },
    listContainer: { flex: 1, backgroundColor: Colors.background },
    listContent: { paddingHorizontal: 24, paddingBottom: 20 },
    separator: { height: 12 },
    todoCard: {
      backgroundColor: Colors.surface,
      borderRadius: 12,
      padding: 16,
      flexDirection: "row",
      alignItems: "flex-start",
      transform: [{ scale: 1 }],
      justifyContent: "space-between",
      shadowColor: Colors.primary,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
      borderWidth: 1,
      borderColor: Colors.border,
    },
    todoContent: { flex: 1, marginRight: 12 },
    todoTitle: { fontSize: 16, fontWeight: "500", color: Colors.text, lineHeight: 22 },
    completedTitle: { textDecorationLine: "line-through", color: Colors.secondaryText },
    toggleButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      borderWidth: 2,
      borderColor: Colors.border,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: Colors.surface,
    },
    toggleTouchArea: { width: "100%", height: "100%", alignItems: "center", justifyContent: "center" },
    completedButton: { backgroundColor: Colors.primary, borderColor: Colors.primary },
    toggleButtonText: { fontSize: 16, fontWeight: "bold", color: Colors.border },
    completedButtonText: { color: Colors.surface },
    modalContainer: { flex: 1 },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.6)",
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 24,
    },
    modalContent: {
      backgroundColor: Colors.surface,
      borderRadius: 16,
      padding: 24,
      width: "100%",
      maxWidth: 400,
      shadowColor: Colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 8,
      borderWidth: 1,
      borderColor: Colors.border,
    },
    modalTitle: { fontSize: 24, fontWeight: "bold", color: Colors.text, textAlign: "center", marginBottom: 24 },
    modalButtons: { flexDirection: "row", justifyContent: "space-between", gap: 12, marginTop: 20 },
    cancelButton: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: Colors.border,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: Colors.background,
    },
    cancelButtonText: { fontSize: 16, fontWeight: "600", color: Colors.text },
    inputGroup: { marginBottom: 20 },
    inputLabel: { fontSize: 14, fontWeight: "600", color: Colors.text, marginBottom: 8 },
    input: {
      height: 48,
      borderWidth: 1,
      borderColor: Colors.border,
      borderRadius: 12,
      paddingHorizontal: 16,
      fontSize: 16,
      color: Colors.text,
      backgroundColor: Colors.surface,
    },
    inputFocused: {
      borderColor: Colors.focusedBorder,
      borderWidth: 2,
      shadowColor: Colors.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 2,
    },
    primaryButton: {
      flex: 1,
      backgroundColor: Colors.primary,
      height: 48,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: Colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    primaryButtonText: { color: Colors.surface, fontSize: 16, fontWeight: "600" },
    loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: Colors.background },
    actionButtons: { flexDirection: "row", marginTop: 12, overflow: "hidden", gap: 10 },
    deleteButton: {
      flex: 1,
      backgroundColor: Colors.error,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: Colors.error,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    deleteButtonText: { color: "#FFFFFF", fontSize: 14, fontWeight: "600" },
    todoCardPressed: { transform: [{ scale: 0.98 }], shadowOpacity: 0.15, elevation: 4 },
    updateButton: {
      flex: 1,
      backgroundColor: Colors.accent,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: Colors.accent,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    updateButtonText: { color: "#FFFFFF", fontSize: 14, fontWeight: "600" },
    menuButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: "transparent",
      borderWidth: 1,
      borderColor: Colors.border,
      alignItems: "center",
      justifyContent: "center",
    },
    menuButtonText: { color: Colors.text, fontSize: 20, fontWeight: "bold", letterSpacing: 1 },
    menuOverlay: { flex: 1, backgroundColor: "transparent" },
    menuDropdown: {
      position: "absolute",
      top: 72,
      right: 24,
      backgroundColor: Colors.surface,
      borderRadius: 12,
      paddingVertical: 6,
      minWidth: 170,
      shadowColor: Colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 8,
      borderWidth: 1,
      borderColor: Colors.border,
    },
    menuItem: { flexDirection: "row", alignItems: "center", gap: 8, paddingVertical: 12, paddingHorizontal: 16 },
    menuItemText: { fontSize: 15, fontWeight: "600", color: Colors.error },
    menuItemTextNormal: { fontSize: 15, fontWeight: "600", color: Colors.text },
    menuIcon: { fontSize: 16 },
    menuSeparator: { height: 1, backgroundColor: Colors.border, marginVertical: 4 },
    emptyState: { alignItems: "center", justifyContent: "center", paddingTop: 80 },
    emptyStateIcon: { fontSize: 48, marginBottom: 12 },
    emptyStateTitle: { fontSize: 18, fontWeight: "700", color: Colors.text, marginBottom: 6 },
    emptyStateSubtitle: { fontSize: 14, color: Colors.secondaryText, textAlign: "center", paddingHorizontal: 40 },
  });