import { StyleSheet } from "react-native";
import { ColorPalette } from "../context/ThemeContext";

export const getAuthStyles = (Colors: ColorPalette) =>
  StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: Colors.background },
    container: { flex: 1 },
    scrollContainer: { flexGrow: 1, justifyContent: "center", paddingHorizontal: 24, paddingVertical: 20 },
    content: { flex: 1, justifyContent: "center" },
    header: { alignItems: "center", marginBottom: 48 },
    title: { fontSize: 32, fontWeight: "bold", color: Colors.text, marginBottom: 8, textAlign: "center" },
    subtitle: { fontSize: 16, color: Colors.secondaryText, textAlign: "center" },
    formCard: {
      backgroundColor: Colors.surface,
      borderRadius: 16,
      padding: 24,
      shadowColor: Colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
      borderWidth: 1,
      borderColor: Colors.border,
    },
    inputGroup: { marginBottom: 20 },
    inputLabel: { fontSize: 14, fontWeight: "600", color: Colors.text, marginBottom: 8 },
    input: {
      height: 48,
      borderWidth: 1,
      borderColor: Colors.border,
      borderRadius: 12,
      paddingHorizontal: 16,
      fontSize: 16,
      color: Colors.text,
      backgroundColor: Colors.surface,
    },
    inputFocused: {
      borderColor: Colors.focusedBorder,
      borderWidth: 2,
      shadowColor: Colors.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 2,
    },
    primaryButton: {
      backgroundColor: Colors.primary,
      height: 48,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 8,
      shadowColor: Colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    primaryButtonDisabled: { backgroundColor: Colors.disabled, opacity: 0.6, shadowOpacity: 0, elevation: 0 },
    primaryButtonText: { color: Colors.surface, fontSize: 16, fontWeight: "600" },
    secondaryButton: { alignItems: "center", marginTop: 32, paddingVertical: 12 },
    secondaryButtonText: { fontSize: 14, color: Colors.secondaryText },
    linkText: { color: Colors.link, fontWeight: "600" },
    gradientOverlay: { position: "absolute", top: 0, left: 0, right: 0, height: 200, opacity: 0.05 },
    welcomeCard: { backgroundColor: Colors.accent, borderRadius: 16, padding: 20, marginBottom: 24, alignItems: "center" },
    welcomeText: { color: Colors.surface, fontSize: 18, fontWeight: "600", textAlign: "center" },
    featureHighlight: { backgroundColor: Colors.secondary, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, alignSelf: "flex-start" },
    featureText: { color: Colors.surface, fontSize: 12, fontWeight: "600" },
  });